// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopAppMerSoftExam.Core.Entities;

namespace ShopAppMerSoftExam.Core.Migrations
{
    [DbContext(typeof(ShopAppDbContect))]
    partial class ShopAppDbContectModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopAppMerSoftExam.Core.Entities.Grup", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code");

                    b.ToTable("GrupDb");
                });

            modelBuilder.Entity("ShopAppMerSoftExam.Core.Entities.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GrupCode")
                        .HasColumnType("int")
                        .HasColumnName("GrupCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code");

                    b.HasIndex("GrupCode");

                    b.ToTable("ProductDb");
                });

            modelBuilder.Entity("ShopAppMerSoftExam.Core.Entities.Product", b =>
                {
                    b.HasOne("ShopAppMerSoftExam.Core.Entities.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("GrupCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grup");
                });
#pragma warning restore 612, 618
        }
    }
}
